- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
Closed #70. Implemented the missing modifier accessors
> 70-Add-more-modifying-accessors-to-DataFrame

- src/DataFrame/DataFrame.class.st
Fixes an error of selecting a row in a GTInspector.
> 94-Selecting-a-row-on-GTInspector-raises-an-error

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
Issue: https://github.com/PolyMathOrg/DataFrame/issues/96
Tasks:
> Boolean operators for DataSeries

- src/DataFrame-Tests/DataFrameInternalTest.class.st
- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
- src/DataFrame/DataFrameInternal.class.st
`nil` is inserted  ito represent missing values.
Fixes #21.
> Added support for DataFrame init with missing values

- src/DataFrame-Type-Tests/DataFrameTypeDetectorTest.class.st
- src/DataFrame-Type/DataFrameTypeDetector.class.st
Also added relevant tests.
Fixes https://github.com/PolyMathOrg/DataFrame/issues/66.
> DataFrameTypeDetector now works with nil

- src/DataFrame-IO/DataFrame.extension.st
- src/DataFrame-Tests/DataFrameInternalTest.class.st
- src/DataFrame/DataFrameInternal.class.st
The method replaces missing values in input file with nil.
Additional tests with the fix for https://github.com/PolyMathOrg/DataFrame/issues/65
> Added method to convert missing values from files

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
TODO: Add methods for filling with Mean, Mode and Median. This is dependent upon the PR https://github.com/PolyMathOrg/DataFrame/pull/102, since it will make the code shorter.
> Added DataSeries fillNilsWith method

- src/DataFrame-Tests/DataFrameInternalTest.class.st
- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataFrame.class.st
- src/DataFrame/DataFrameInternal.class.st
- src/DataFrame/DataSeries.class.st
DataSeries can remove nils using the method `removeNils`
DataFrame can remove nils from rows and columns using methods:
- `removeColumnsWithNilsAtRow:`
- `removeColumnsWithNilsAtRowNamed:`
- `removeRowsWithNilsAtColumn:`
- `removeRowsWithNilsAtColumnNamed:`
Added relevant tests for these methods
> Added ability to remove nil from DataFrame and Series

- src/DataFrame/DataFrame.class.st
DataFrame>>size returns number of rows instead of counting by do:
> 114-DataFramesize-is-very-slow-because-it-counts-by-DataFramedo

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataFrame.class.st
- src/DataFrame/DataSeries.class.st
Fixes https://github.com/PolyMathOrg/DataFrame/issues/58.
`innerJoin`, `outerJoin`, `leftJoin`, `rightJoin` are joins based on `rowNames` only. Since row names are unique, resulting code is bit simpler (and faster).
Other joins are with arbitary columns. It is possible to combine both of them, but it will make the code much more complex.
There are multiple tests added to handle edge cases. Some tests may seem repetitive, because of output of joins, but they are kept to highlight differences between different methods.
`#() asDataSeries` was not working - https://github.com/PolyMathOrg/DataFrame/commit/9857c5c30608cdf820734c2c92acd0abb160c7c5 fixes it.
> Joins between dataframes and nil init of dataseries

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
Final (hopefully) PR for missing data issues.
> Added methods to fill nils with Mean, Mode, Median

- src/BaselineOfDataFrame/BaselineOfDataFrame.class.st
- src/DataFrame-IO-Tests/DataFrameJsonReaderTest.class.st
- src/DataFrame-IO-Tests/DataFrameJsonWriterTest.class.st
- src/DataFrame-IO-Tests/TestJsonStrings.class.st
- src/DataFrame-IO/DataFrame.extension.st
- src/DataFrame-IO/DataFrameJsonReader.class.st
- src/DataFrame-IO/DataFrameJsonWriter.class.st
Fixes https://github.com/PolyMathOrg/DataFrame/issues/97.
There are 5 types of json to which you can read/write: `columns` `index` `values` `split` `records`.
The reader converts the json into appropriate types. When reading, the columns and rows do not maintain same order, due to structure of Dictionary (no inherent ordering). Sorting them is not done by default as it may be time consuming.
> Json support

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
Closed #118. Improved the API of joins by replacing join:leftColumn:rightColumn: with join:onLeft:onRight: and introducing join:on:
> 118-Improve-API-of-joins

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
creating empty dataframes with column/row names
> 122-DataFrame-classwithRowscolumnNames-fails-when-the-given-rows-are-empty

- src/DataFrame-Tests/DataFrameTest.class.st
I submit this pull request to suggest a new test method `DataFrameTest >> #testRangeError`.
#testRangeError makes it explicit that calling #range on a DataFrame object containing non-numerical columns throw an exception. In the current implementation, the pre-condition is implicit but with this new test it becomes an explicit part of the contract for DataFrame.
Note that these suggestions are adapted from a test amplification tool called SmallAmp (https://github.com/mabdi/small-amp). SmallAmp executes existing tests, sees which parts of the class under test are not covered and then suggests improvements on the test methods.
I hope you will accept this pull request. It would illustrate that SmallAmp makes relevant suggestions.
Mehrdad Abdi.
> Adding new test method: DataFrameTest>>#testRangeError

- src/DataFrame-IO/DataFrame.extension.st
- src/DataFrame-IO/DataFrameCsvReader.class.st
- src/DataFrame-Type-Tests/DataFrameTypeDetectorTest.class.st
- src/DataFrame-Type/DataFrameTypeDetector.class.st
Other programs output their boolean values in CSV files as uppercase (Excel, R) or sentence case (python). This change makes `DataFrameTypeDetector>>canAllBeBoolean` less stringent so that any case is accepted.
> Allow booleans to be any case.

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
Returns a collection of all columns. 
`df := DataFrame withRows: #( #('Alice' 24 'F') #('Bob' 30 'M') #('David' 22 'M').`
`df columns.`
This returns a collection as below.
`#( #('Alice' 'Bob' 'David') #(24 30 22) #('M' 'F' 'M') ).`
> implemented columns method

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
Cumulative Sum in Statistics is used to show the summation of data as it grows with time (updated when every new number is added to the sequence).  It's significance is used to measure total contribution so far of a measure against time, majorly used in 
Statistical Anaysis.
`DataSeries >> cumulativeSum`
`Category : statistics`
Example : 
`series := DataSeries withValues: #( nil 1 2 3 nil 4 5 0 6 nil 7 8 ).`
`series cumulativeSum.`
Returns a DataSeries as below:
| Key | Value |
| --- | --- |
| 1 | 0 |
| 2 | 1 |
| 3 | 3 |
| 4 | 6 |
| 5 | 6 |
| 6 | 10 |
| 7 | 15 |
| 8 | 15 |
| 9 | 21 |
| 10 | 21 |
| 11 | 28 |
| 12 | 36 |
> Added cumulativeSum method (tested!)

- src/DataFrame-IO/DataFrameCsvReader.class.st
- src/DataFrame-IO/DataFrameReader.class.st
- src/DataFrame-Type-Tests/DataFrameTypeDetectorTest.class.st
- src/DataFrame-Type/DataFrameTypeDetector.class.st
This pull request adds in the ability for `DataFrameCsvReader` and `DataFrameTypeDetector` to be given a mapping of types. This allows skipping the (potentially slow) process of guessing the types of the columns. The `columnTypes:` message has been added to both classes which takes a dictionary with the following format:
```
{
<columnName> -> <ClassName>
<columnName> -> <block>
}
```
where the column name is given as the key and the values can be either a string, specifying one of the standard types that `DataFrameTypeDetector` performs; or a block, which performs custom conversion. The standard types map on to one of the conversion messages already implemented whereas if a block is given then it is assumed to take the column as a the argument and return a transformed version of the …
> Explicit column types

- src/DataFrame/DataFrame.class.st
- src/DataFrame/DataSeries.class.st
This method it called in multiple occasions when we want to have the column of a data frame. 
This PR speed it up by removing the need for intermediate collections
> Speed up DataFrame>>#column:

- src/DataFrame-Type/DataFrameTypeDetector.class.st
Done by aksing the dataframe to build all columns in one go instead of doing it one by one
> Speedup type detector

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
#groupBy:aggregateUsing: was taking 4.5sec on a dataset to count the occurences of a value, now it takes 1.3sec with my speed up I also added an alternative where we group by the same dataset and now it takes 0.3sec
> Speed up grouping and aggregating

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
Allow arithmetic operations with nils in data series
If a nil is present, we will keep a nil in the result.
+ Some cleanings
> Arithmetic operations should be possible with nils

- src/DataFrame-Math/DataPearsonCorrelationMethod.class.st
- src/DataFrame-Tests/DataFrameStatsTest.class.st
- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataFrame.class.st
- src/DataFrame/DataSeries.class.st
This PR fixes various bugs:
- #isNumerical should return true for columns with numbers and nils
- #sum should work on DataSeries with nil values (nils are considered 0)
- #correlationMatrix should be able to compute the correlation for numerical columns with nil values
- Make #average work as #mean in pandas
- Copying a DataFrame pointed to the same internal structure and was not a real copy
All the behavior changes here are matching the behavior of Pandas
> Fix various bugs

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
* #closeTo: now only use #closeTo: on numbers and not on all objects because Object>>#closeTo: is a hack from the Finder
* Add #closeTo:precision: to make DataFrame be able to be a parameter of #assert:closeTo: that relies on it
* Add tests
> Improve management of #closeTo:

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
Things to improve:
- Manage outer and inner join
- Add a concatenation that manages multiple data frame at the same time for performances
- Manage dataframes with diffirent columns
- Manage dataframes with same indexe
Fixes #216
> Add a basic concatenation

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
These methods are similar to the [.count() ](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.count.html#pandas.DataFrame.count)method in pandas.
Also wrote tests for these methods.
> Add DataSeries>>#countNils and #countNonNils

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
This is the equivalent of pandas.ffils().
Tests have also been written for this method.
This is a fix for issue #221
> Added DataFrame>> #replaceNilsWithNextRowValue 

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
Also wrote tests for #removeDuplicates as #uniqueValues didn't have any tests.
> Changed method name of uniqueValues to removeDuplicates.

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
Tests have been written to check if these methods work properly if a dataseries has nil values and if it doesn't have nil values.
This fixes issue #227.
> Statistical methods such as stdev, max and min can now handle nils.

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
#numericalColumns currently returns a DataFrame of only the numerical columns in the original DataFrame, it should return an array of numerical columns.
> #numericalColumns now returns an array of all numerical columns

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
This method is similar to [pandas.describe()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) and it will be useful in providing a statistic description of the dataframe.
Tests are also written for this method.
This fixes issue #167
> Added describe method for numeric dataframes

- src/DataFrame-Tests/DataFrameTest.class.st
> Added tests for untested methods

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
I've implemented a method `toMarkdown` so that DataFrames can be converted to a Markdown formatted table.
```smallTalk
df := DataFrame withRows:
#( #( 'Barcelona' 1.609 true ) 
#( 'Dubai' 2.789 true )
#( 'London' 8.788 false ) ).
df rowNames: #( 'A' 'B' 'C' ).
df columnNames: #( 'City' 'Population' 'BeenThere' ).
df toMarkdown.
```
This should return a string which can be copy-pasted in an editor which supports Markdown.
```
| #   | City        | Population | BeenThere | 
| --- | ----------- | ---------- | --------- | 
| 'A' | 'Barcelona' | 1.609      | true      | 
| 'B' | 'Dubai'     | 2.789      | true      | 
| 'C' | 'London'    | 8.788      | false     | 
```
It would look like this once this text is pasted in a Markdown supported editor : 
| #   | City        | Population | …
> Added DataFrame>> #toMarkdown along with tests

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
I've implemented a method `toLatex` so that DataFrames can be converted to a Latex formatted table.
```
df := DataFrame withRows:
#( #( 'Barcelona' 1.609 true ) 
#( 'Dubai' 2.789 true )
#( 'London' 8.788 false ) ).
df rowNames: #( 'A' 'B' 'C' ).
df columnNames: #( 'City' 'Population' 'BeenThere' ).
df toLatex.
```
This should return a string which can be copy-pasted in a latex-text editor.
```
\begin{tabular}{|l|l|l|l|}
\hline
\#  & City        & Population & BeenThere\\
\hline
'A' & 'Barcelona' & 1.609      & true     \\
\hline
'B' & 'Dubai'     & 2.789      & true     \\
\hline
'C' & 'London'    & 8.788      & false    \\
\hline
\end{tabular}
```
It would look like this once this text is compiled in a Latex supported editor :
> Added DataFrame>> #toLatex with tests

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
I've implemented a method `toHtml` so that DataFrames can be converted to an html table.
```
df := DataFrame withRows:
#( #( 'Barcelona' 1.609 true ) 
#( 'Dubai' 2.789 true )
#( 'London' 8.788 false ) ).
df rowNames: #( 'A' 'B' 'C' ).
df columnNames: #( 'City' 'Population' 'BeenThere' ).
df toHtml.
```
This should return a string which can be copy-pasted in an html editor.
```
<table border="1" class="dataframe">
<thead>
<tr style="text-align: left;">      <th>#  </th>
<th>City       </th>
<th>Population</th>
<th>BeenThere</th>
</tr>
</thead>
<tbody>
<tr>      <th>'A'</th>
<td>'Barcelona'</td>
<td>1.609     </td>
<td>true     </td>
</tr>
<tr>      <th>'B'</th>
<td>'Dubai'    </td>
<td>2.789     </td>
<td>true     </td>
</tr>
<tr>      <th>'C'</th>
<td>'London'   </td>
<td>8.788     </td> …
```
> Added DataFrame>> #toHtml

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
I've implemented a method `toString` so that DataFrames can be converted to a string table.
```
df := DataFrame withRows:
#( #( 'Barcelona' 1.609 true ) 
#( 'Dubai' 2.789 true )
#( 'London' 8.788 false ) ).
df rowNames: #( 'A' 'B' 'C' ).
df columnNames: #( 'City' 'Population' 'BeenThere' ).
df toString.
```
This should return a string which looks like a DataFrame
```
'A'  'Barcelona'  1.609       true       
'B'  'Dubai'      2.789       true       
'C'  'London'     8.788       false      
```
> Added DataFrame>> #toString. Fixed #126.

- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame/DataFrame.class.st
DataFrame>> #addRow: and #addRowAtPosition:  now considers key ordering.
> Fixed #106. DataFrame>> #addRow: now considers key ordering

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
DataSeries>> #removeNils now removes nil values from a data series and #withoutNils returns a copy of the data series without nils.
> Fixed #257. DataSeries>> #removeNils and #withoutNils work differently

- src/DataFrame/DataFrame.class.st
Are these examples alright? I tried to limit them to 1 or 2 lines so that they don't take up majority of the method definition. If they are alright, I'll write executable commands for more methods of the DataFrame class.
> Added runnable examples for DataFrame

- src/DataFrame-IO-Tests/DataFrameCsvWriterTest.class.st
- src/DataFrame-IO-Tests/TestCsvStrings.class.st
- src/DataFrame-IO/DataFrameCsvWriter.class.st
This PR is to provide more options to write CSV files in desired formats.
The inst var `fieldWriter` holds a symbol to be passed to NeoCSV writer to change the presentation of the values.
You can set it by `useRawFieldWriter`, `useQuotedFieldWriter`, `useOptionalQuotedFieldWriter` and `useObjectFieldWriter`.
By default, it uses the quoted field writer (same as the original implementation of the current `DataFrameCsvWriter`).
The inst var `rowNameEnabled` holds a boolean to decide whether the writer outputs row names into the CSV file.
You can set it by `enableRowName` and `disableRowName`.
By default, it is disabled (same as the original implementation of the current `DataFrameCsvWriter`).
> add more formatting options to DataFrameCsvWriter

- src/DataFrame-IO-Tests/DataFrameCsvReaderTest.class.st
- src/DataFrame-IO/DataFrame.extension.st
- src/DataFrame-IO/DataFrameCsvReader.class.st
This is commonly found in multiple CSV datasets (see for example See ftp://ftp.ncbi.nlm.nih.gov/genomes/README_assembly_summary.txt)
Add tests.
> Add method to read CSV string with option to skip N lines from header

- src/DataFrame-IO-Tests/DataFrameCsvReaderTest.class.st
- src/DataFrame-IO/DataFrame.extension.st
- src/DataFrame-IO/DataFrameCsvReader.class.st
This PR address the issue in #278, to enable reading from CSV file and manually setting the columns with a delimiter Character.
Now the data frame reader column names are not overwritten by default if they were previously set.
> Create DataFrame from CSV setting the column names and separator

- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame/DataSeries.class.st
Change DataSeries>>#summary to bring it more in line with Python's pandas describe() by adding Count and Stdev, renaming 1st Qu., Median, 3rd Qu. to 25%, 50% and 75%, as well as re-ordening the list.
> Change DataSeries>>#summary a bit

- src/DataFrame-Tests/DataFrameAggrGroupTest.class.st
- src/DataFrame-Tests/DataFrameHeadTailTest.class.st
- src/DataFrame-Tests/DataFrameInternalTest.class.st
- src/DataFrame-Tests/DataFrameStatsTest.class.st
- src/DataFrame-Tests/DataFrameTest.class.st
- src/DataFrame-Tests/DataPearsonCorrelationMethodTest.class.st
- src/DataFrame-Tests/DataSeriesTest.class.st
- src/DataFrame-Tests/package.st
- src/DataFrame/Array.extension.st
- src/DataFrame/Behavior.extension.st
- src/DataFrame/Collection.extension.st
- src/DataFrame/DataCorrelationMethod.class.st
- src/DataFrame/DataFrame.class.st
- src/DataFrame/DataFrameInternal.class.st
- src/DataFrame/DataPearsonCorrelationMethod.class.st
- src/DataFrame/DataSeries.class.st
- src/DataFrame/String.extension.st
- src/DataFrame/package.st
Add support for shuffling a DataFrame.
> Add shuffling

- src/DataFrame-IO-Tests/DataFrameCsvWriterTest.class.st
- src/DataFrame-IO-Tests/TestCsvStrings.class.st
- src/DataFrame-IO/DataFrame.extension.st
- src/DataFrame-IO/DataFrameCsvWriter.class.st
Fixed #284.
I added three new methods:
- writeToCsv: withColumnNames: withRowNames:
- writeToCsv: withColumnNames:
- writeToCsv: withRowNames:
Also changed the implementation of `writeToCsv`
```
writeToCsv: aFileReference
self writeToCsv: aFileReference withColumnNames: true withRowNames: true
```
Also added tests for the methods.
> Added writeToCsv: withColumnNames: withRowNames:
